# Generated by Django 5.0b1 on 2023-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=30, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=30, verbose_name='slug')),
                ('contents', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью')),
                ('create_date', models.DateField(verbose_name='дата создания')),
                ('publication_date', models.DateField(verbose_name='дата публикации')),
                ('views_count', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('article_name',),
            },
        ),
    ]
