# Generated by Django 5.0b1 on 2023-12-12 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.FloatField(default=0, verbose_name='версия')),
                ('version_name', models.CharField(max_length=50, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=True, unique=True, verbose_name='активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='наименование продукта')),
            ],
        ),
    ]
