# Generated by Django 5.0b1 on 2023-12-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
