# Generated by Django 5.0b1 on 2023-12-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_version_is_active_alter_version_version_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='product',
            new_name='prod',
        ),
        migrations.AddField(
            model_name='product',
            name='vers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.version', verbose_name='версия'),
        ),
    ]
