# Generated by Django 5.0b1 on 2023-12-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_vers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('prod',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='vers',
        ),
        migrations.AlterField(
            model_name='version',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='наименование продукта'),
        ),
    ]
